version: ">= 0.16"
formatter: markdown table

content: |-
  {{ .Header }}
  {{ .Requirements }}
  {{ .Providers }}
  {{ .Modules }}
  {{ .Resources }}
  {{ .Inputs }}
  {{ .Outputs }}

settings:
  description: true
